# Generated by Django 2.2 on 2022-04-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20220406_2055'),
        ('tweets', '0002_auto_20220404_0830'),
        ('tweets', '0005_tweet_parent'),
    ]

    operations = [
    ]
